spring:
  cloud:
    gateway:
      routes:
        - id: database
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: front
          uri: http://localhost:8082
          predicates:
            - Path=/front/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true