spring:
  cloud:
    gateway:
      routes:
        - id: database
          uri: http://localhost:8081
          predicates:
            - Path=/data/**
        - id: front
          uri: http://localhost:8082
          predicates:
            - Path=/front/**