spring:
  cloud:
    gateway:
      routes:
        - id: database
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: front
          uri: http://localhost:8082
          predicates:
            - Path=/front/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  boot:
    admin:
      client:
        url: http://localhost:8787

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, info
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  info:
    env:
      enabled: true
info:
  application:
    name: "Gateway service"
    version: "1.0.0"
    description: "Gateway"