spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersDB
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always





