spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersDB
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  env:
    enabled: true
  info:
    enabled: true
    env:
      enabled: true
    application:
      name: "UserData microservice"
      version: "1.0.0"
      description: "User Register"




